export const ICAO_AIRLINES = {
  'ACA': 'Air Canada',
  'JZA': 'Jazz Aviation',
  'ROU': 'Air Canada Rouge',
  'WJA': 'WestJet',
  'WEJ': 'WestJet Encore',
  'WEN': 'WestJet Link',
  'SWG': 'Sunwing Airlines',
  'TSC': 'Air Transat',
  'FLI': 'Flair Airlines',
  'POE': 'Porter Airlines',
  'CJT': 'Cargojet Airways',
  'KFA': 'Kelowna Flightcraft',
  'CGP': 'Cargo Plus',
  'CXA': 'XiamenAir',
  'CPA': 'Cathay Pacific',
  'CAL': 'China Airlines',
  'EVA': 'EVA Air',
  'PAL': 'Philippine Airlines',
  'KAL': 'Korean Air',
  'ANA': 'All Nippon Airways',
  'JAL': 'Japan Airlines',
  'QFA': 'Qantas',
  'ANZ': 'Air New Zealand',
  'BAW': 'British Airways',
  'AFR': 'Air France',
  'DLH': 'Lufthansa',
  'KLM': 'KLM Royal Dutch Airlines',
  'ICE': 'Icelandair',
  'AMX': 'Aeromexico',
  'ASA': 'Alaska Airlines',
  'QXE': 'Horizon Air',
  'DAL': 'Delta Air Lines',
  'UAL': 'United Airlines',
  'AAL': 'American Airlines',
  'UPS': 'UPS Airlines',
  'FDX': 'FedEx Express',
  'PAC': 'Polar Air Cargo',
  'GTI': 'Atlas Air',
  'HAL': 'Hawaiian Airlines',
  'SIA': 'Singapore Airlines',
  'AIC': 'Air India',
  'CHH': 'Hainan Airlines',
  'CSN': 'China Southern Airlines',
  'CCA': 'Air China',
  'CES': 'China Eastern Airlines',
  'THY': 'Turkish Airlines',
  'UAE': 'Emirates',
  'QTR': 'Qatar Airways',
  'CMP': 'Copa Airlines',
  'FFT': 'Frontier Airlines',
  'NKS': 'Spirit Airlines',
  'JBU': 'JetBlue Airways',
  'SWA': 'Southwest Airlines',
  'AAY': 'Allegiant Air',
  'SYX': 'Sun Country Airlines',
  'VTE': 'Volotea',
  'RYR': 'Ryanair',
  'EZY': 'easyJet',
  'WZZ': 'Wizz Air',
  'NAX': 'Norwegian Air Shuttle',
  'FIN': 'Finnair',
  'SAS': 'Scandinavian Airlines',
  'IBE': 'Iberia',
  'AZA': 'ITA Airways',
  'SWR': 'Swiss International Air Lines',
  'AUA': 'Austrian Airlines',
  'SNB': 'Brussels Airlines',
  'LOT': 'LOT Polish Airlines',
  'TAP': 'TAP Air Portugal',
  'AFL': 'Aeroflot',
  'VIR': 'Virgin Atlantic',
  'ETD': 'Etihad Airways',
  'OMA': 'Oman Air',
  'GFA': 'Gulf Air',
  'MEA': 'Middle East Airlines',
  'RJA': 'Royal Jordanian',
  'MSR': 'EgyptAir',
  'ETH': 'Ethiopian Airlines',
  'KQA': 'Kenya Airways',
  'SAA': 'South African Airways',
  'RAM': 'Royal Air Maroc',
  'AHY': 'Azerbaijan Airlines',
  'UZB': 'Uzbekistan Airways',
  'HYT': 'YTO Cargo Airlines',
  'CSO': 'ShunDong Airlines',
  'OKA': 'Okay Airways',
  'DKH': 'Juneyao Airlines',
  'CQH': 'Spring Airlines',
  'CSC': 'Sichuan Airlines',
  'CRK': 'Hong Kong Airlines',
  'HDA': 'Cathay Dragon',
  'MGL': 'MIAT Mongolian Airlines',
  'KOR': 'Air Koryo',
  'VJC': 'VietJet Air',
  'HVN': 'Vietnam Airlines',
  'BKP': 'Bangkok Airways',
  'THA': 'Thai Airways',
  'MAS': 'Malaysia Airlines',
  'AXM': 'AirAsia',
  'GIA': 'Garuda Indonesia',
  'BTK': 'Batik Air',
  'LNI': 'Lion Air',
  'CTV': 'Citilink',
  'CEB': 'Cebu Pacific',
  'PXA': 'Air Niugini',
  'FJI': 'Fiji Airways',
  'TGW': 'Scoot',
  'VOZ': 'Virgin Australia',
  'JST': 'Jetstar Airways',
  'NCA': 'Nippon Cargo Airlines',
  'ADO': 'Air Do',
  'SNA': 'Solaseed Air',
  'SFJ': 'StarFlyer',
  'SKY': 'Skymark Airlines',
  'FDA': 'Fuji Dream Airlines',
  'APJ': 'Peach Aviation',
  'WAJ': 'AirAsia Japan',
  'JJP': 'Jetstar Japan',
  'TTW': 'Tigerair Taiwan',
  'ITW': 'Tigerair Taiwan',
  'TNA': 'TransAsia Airways',
  'FAT': 'Far Eastern Air Transport',
  'MDA': 'Mandarin Airlines',
  'UIA': 'Uni Air',
  'EAA': 'AirExplore',
  'TVS': 'Smartwings',
  'QS': 'Smartwings',
  'ENT': 'Enter Air',
  'LLC': 'Small Planet Airlines',
  'BGH': 'BH Air',
  'CAI': 'Corendon Airlines',
  'SXS': 'SunExpress',
  'PGT': 'Pegasus Airlines',
  'IZG': 'Izmir Airlines',
  'OHY': 'Onur Air',
  'SHY': 'Sky Airlines',
  'KIL': 'Kuban Airlines',
  'DNV': 'Donavia',
  'NWS': 'Nordwind Airlines',
  'KAR': 'Ikar Airlines',
  'RLU': 'RusLine',
  'SYL': 'Yakutia Airlines',
  'TYA': 'NordStar',
  'S7': 'S7 Airlines',
  'SBI': 'S7 Airlines',
  'UTO': 'Utair',
  'PBD': 'Pobeda',
  'DP': 'Pobeda',
  'MOV': 'VIM Airlines',
  'RSO': 'Red Wings Airlines',
  'RWZ': 'Red Wings Airlines',
  'AZO': 'Azimuth',
  'NLU': 'Alrosa',
  'IKR': 'KrasAvia',
  'KGL': 'Kogalymavia',
  'KAP': 'Aircompany Arctic',
  'AUL': 'Arkhangelsk Airlines',
  'AKX': 'Aktobe',
  'CRV': 'Caravelle',
  'TGA': 'Transglobe Airways',
  'TRA': 'Transavia',
  'TFL': 'TUI fly Netherlands',
  'TUI': 'TUI Airways',
  'HLX': 'TUIfly',
  'JAF': 'TUI fly Belgium',
  'BLX': 'TUI fly Nordic',
  'CFG': 'Condor',
  'EXS': 'Jet2.com',
  'TOM': 'TUI Airways',
  'MON': 'Monarch Airlines',
  'TCX': 'Thomas Cook Airlines',
  'FCA': 'First Choice Airways',
  'BMA': 'BMI',
  'BMI': 'BMI Regional',
  'VEX': 'Virgin Express',
  'SN': 'Brussels Airlines',
  'DAT': 'Danish Air Transport',
  'WIF': 'Widerøe',
  'DXH': 'East Star Airlines',
  'LKE': 'Lucky Air',
  'PNR': 'Pan American World Airways',
  'TWA': 'Trans World Airlines',
  'EAL': 'Eastern Air Lines',
  'BNF': 'Braniff International Airways',
  'RPA': 'Republic Airways',
  'SKW': 'SkyWest Airlines',
  'ENY': 'Envoy Air',
  'EDV': 'Endeavor Air',
  'MTR': 'MetroJet',
  'JIA': 'PSA Airlines',
  'PDT': 'Piedmont Airlines',
  'GJS': 'GoJet Airlines',
  'AWQ': 'Indonesia AirAsia',
  'LAL': 'Air Labrador',
  'MAL': 'Morningstar Air Express',
  'NCB': 'North Cariboo Air',
  'CEN': 'Central Mountain Air',
  'GLR': 'Glacier Air',
  'HCA': 'Harbour Air',
  'KWA': 'Air Creebec',
  'PCO': 'Pacific Coastal Airlines',
  'TGO': 'Transport Canada',
  'RCMP': 'Royal Canadian Mounted Police'
};

export const REGISTRATION_PREFIXES = {
  'C-': 'Canadian Registration',
  'N': 'US Registration',
  'G-': 'UK Registration',
  'VH-': 'Australian Registration',
  'ZK-': 'New Zealand Registration',
  'B-': 'China/Taiwan Registration',
  'JA': 'Japan Registration',
  'HL': 'South Korea Registration',
  '9V-': 'Singapore Registration',
  'D-': 'German Registration',
  'F-': 'French Registration',
  'PH-': 'Dutch Registration',
  'HB-': 'Swiss Registration',
  'OE-': 'Austrian Registration',
  'EI-': 'Irish Registration',
  'EC-': 'Spanish Registration',
  'CS-': 'Portuguese Registration',
  'I-': 'Italian Registration',
  'TC-': 'Turkish Registration',
  'SU-': 'Egyptian Registration',
  'A6-': 'UAE Registration',
  'A7-': 'Qatar Registration',
  '9K-': 'Kuwait Registration',
  'HZ-': 'Saudi Registration',
  'VT-': 'Indian Registration',
  'PK-': 'Indonesian Registration',
  '9M-': 'Malaysian Registration',
  'HS-': 'Thai Registration',
  'RP-': 'Philippine Registration',
  'CC-': 'Chilean Registration',
  'LV-': 'Argentine Registration',
  'PR-': 'Brazilian Registration',
  'PT-': 'Brazilian Registration',
  'XA-': 'Mexican Registration',
  'XB-': 'Mexican Registration',
  'XC-': 'Mexican Registration'
};

export function inferOperator(flight, reg, ownOp) {
  if (ownOp && ownOp.trim() !== '') return ownOp;
  
  if (flight) {
    const flightTrimmed = flight.trim().toUpperCase();
    const prefix3 = flightTrimmed.substring(0, 3);
    if (ICAO_AIRLINES[prefix3]) {
      return ICAO_AIRLINES[prefix3];
    }
  }

  if (reg) {
    const regUpper = reg.toUpperCase();
    for (const prefix in REGISTRATION_PREFIXES) {
      if (regUpper.startsWith(prefix)) {
        return `Private (${REGISTRATION_PREFIXES[prefix]})`;
      }
    }
  }

  return 'Unknown Operator';
}
